name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Mise à jour vers la v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Ajout de guillemets pour la version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then 
          pip install -r requirements.txt
        else 
          echo "Pas de requirements.txt trouvé."
        fi

    - name: Run tests
      run: |
        if [ -f test.py ]; then 
          python -m pytest test.py  # Utilisation de pytest plutôt que d'exécuter directement
        else 
          echo "Aucun fichier test.py trouvé."
          exit 0  # Sortie propre si aucun test n'est trouvé
        fi

